spring:
  cloud:
    gateway:
      server:
        webflux:
          trusted-proxies: ".*"
      globalcors:
        cors-configurations:
          '[/api/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
