package com.finki.vladislavangelovski.ai_service.history;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.finki.vladislavangelovski.common.dto.QaChatHistoryItem;
import com.finki.vladislavangelovski.common.dto.QaChatKind;
import com.finki.vladislavangelovski.common.dto.QaClaimRequest;
import com.finki.vladislavangelovski.common.dto.QaClaimResponse;
import com.finki.vladislavangelovski.common.dto.QaQuestionRequest;
import com.finki.vladislavangelovski.common.dto.QaQuestionResponse;
import com.finki.vladislavangelovski.common.dto.Verdict;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class JdbcQaChatHistoryRepositoryTests {
  private JdbcTemplate jdbc;
  private JdbcQaChatHistoryRepository repository;

  @BeforeEach
  void setUp() {
    JdbcDataSource ds = new JdbcDataSource();
    ds.setURL("jdbc:h2:mem:qa_history;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
    ds.setUser("sa");
    ds.setPassword("");

    jdbc = new JdbcTemplate(ds);
    repository = new JdbcQaChatHistoryRepository(jdbc, new ObjectMapper());

    jdbc.execute("DROP TABLE IF EXISTS qa_chat_history");
    jdbc.execute(
        """
            CREATE TABLE qa_chat_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id VARCHAR(128) NOT NULL,
                user_name VARCHAR(256),
                chat_type VARCHAR(16) NOT NULL,
                prompt TEXT NOT NULL,
                image_ref TEXT,
                top_k INTEGER,
                response_json TEXT NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            )
            """);
  }

  @Test
  void savesAndLoadsQuestionHistory() {
    QaQuestionRequest request =
        new QaQuestionRequest("Is CVE-2021-44228 present?", "nginx:1.25", 4);
    QaQuestionResponse response =
        new QaQuestionResponse("Answer", List.of(), List.of("CVE-2021-44228"), List.of("openssl"));

    repository.saveQuestion("user-1", "alice", request, response);

    List<QaChatHistoryItem> items = repository.findRecentByUser("user-1", 10);
    assertEquals(1, items.size());

    QaChatHistoryItem item = items.get(0);
    assertEquals(QaChatKind.QUESTION, item.kind());
    assertEquals("Is CVE-2021-44228 present?", item.prompt());
    assertEquals("nginx:1.25", item.imageRef());
    assertEquals(4, item.k());
    assertNotNull(item.questionResponse());
    assertNull(item.claimResponse());
    assertEquals("Answer", item.questionResponse().answer());
  }

  @Test
  void savesAndLoadsClaimHistory() {
    QaClaimRequest request = new QaClaimRequest("This image is low risk.", "nginx:1.25", 3);
    QaClaimResponse response =
        new QaClaimResponse(Verdict.INSUFFICIENT, "Need more evidence.", List.of());

    repository.saveClaim("user-1", "alice", request, response);

    List<QaChatHistoryItem> items = repository.findRecentByUser("user-1", 10);
    assertEquals(1, items.size());

    QaChatHistoryItem item = items.get(0);
    assertEquals(QaChatKind.CLAIM, item.kind());
    assertEquals("This image is low risk.", item.prompt());
    assertEquals("nginx:1.25", item.imageRef());
    assertEquals(3, item.k());
    assertNull(item.questionResponse());
    assertNotNull(item.claimResponse());
    assertEquals(Verdict.INSUFFICIENT, item.claimResponse().verdict());
  }
}
