package com.finki.vladislavangelovski.ai_service.history;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.finki.vladislavangelovski.common.dto.Citation;
import com.finki.vladislavangelovski.common.dto.QaConversationHistoryItem;
import com.finki.vladislavangelovski.common.dto.QaQuestionRequest;
import com.finki.vladislavangelovski.common.dto.QaQuestionResponse;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class JdbcQaConversationRepositoryTests {
  private JdbcQaConversationRepository repository;

  @BeforeEach
  void setUp() {
    JdbcDataSource ds = new JdbcDataSource();
    ds.setURL("jdbc:h2:mem:qa_conversations;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
    ds.setUser("sa");
    ds.setPassword("");

    JdbcTemplate jdbc = new JdbcTemplate(ds);
    repository = new JdbcQaConversationRepository(jdbc, new ObjectMapper());

    jdbc.execute("DROP TABLE IF EXISTS qa_chat_messages");
    jdbc.execute("DROP TABLE IF EXISTS qa_chat_conversations");

    jdbc.execute(
        """
            CREATE TABLE qa_chat_conversations (
                conversation_id UUID PRIMARY KEY,
                user_id VARCHAR(256) NOT NULL,
                user_name VARCHAR(256),
                chat_scope_id VARCHAR(512) NOT NULL,
                image_ref TEXT,
                title TEXT NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            )
            """);

    jdbc.execute(
        """
            CREATE TABLE qa_chat_messages (
                message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                conversation_id UUID NOT NULL,
                role VARCHAR(16) NOT NULL,
                content TEXT NOT NULL,
                citations_json TEXT,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                CONSTRAINT fk_qa_chat_messages_conversation
                    FOREIGN KEY (conversation_id) REFERENCES qa_chat_conversations (conversation_id)
                    ON DELETE CASCADE
            )
            """);
  }

  @Test
  void appendsAndLoadsConversationHistory() {
    QaUserContext userContext = new QaUserContext("user-1", "alice");
    QaQuestionRequest request =
        new QaQuestionRequest(
            "How should I remediate this image?",
            "nginx:1.25",
            6,
            "ctx",
            List.of(),
            "image|nginx:1.25",
            null);
    QaQuestionResponse response =
        new QaQuestionResponse(
            "Prioritize critical CVEs first.",
            List.of(new Citation("CVE-2021-44228", "https://nvd.nist.gov/vuln/detail/CVE-2021-44228", "Evidence")),
            List.of("CVE-2021-44228"),
            List.of("log4j"));

    String conversationId = repository.appendQuestionExchange(userContext, request, response);

    assertNotNull(conversationId);

    List<QaConversationHistoryItem> history =
        repository.findRecentConversations("user-1", "image|nginx:1.25", 10);

    assertEquals(1, history.size());
    QaConversationHistoryItem item = history.get(0);
    assertEquals(conversationId, item.conversationId());
    assertEquals(2, item.messages().size());
    assertEquals("user", item.messages().get(0).role());
    assertEquals("assistant", item.messages().get(1).role());
    assertEquals(1, item.messages().get(1).citations().size());
  }

  @Test
  void continuesConversationWhenConversationIdProvided() {
    QaUserContext userContext = new QaUserContext("user-1", "alice");

    String conversationId =
        repository.appendQuestionExchange(
            userContext,
            new QaQuestionRequest(
                "Question one", "nginx:1.25", 6, "ctx", List.of(), "image|nginx:1.25", null),
            new QaQuestionResponse("Answer one", List.of(), List.of(), List.of()));

    repository.appendQuestionExchange(
        userContext,
        new QaQuestionRequest(
            "Question two",
            "nginx:1.25",
            6,
            "ctx",
            List.of(),
            "image|nginx:1.25",
            conversationId),
        new QaQuestionResponse("Answer two", List.of(), List.of(), List.of()));

    List<QaConversationHistoryItem> history =
        repository.findRecentConversations("user-1", "image|nginx:1.25", 10);

    assertEquals(1, history.size());
    assertEquals(4, history.get(0).messages().size());
    assertEquals("Question two", history.get(0).messages().get(2).content());
    assertEquals("Answer two", history.get(0).messages().get(3).content());
  }

  @Test
  void deletesConversationByUserId() {
    QaUserContext userContext = new QaUserContext("user-1", "alice");

    String conversationId =
        repository.appendQuestionExchange(
            userContext,
            new QaQuestionRequest(
                "Can I remove this chat?",
                "nginx:1.25",
                6,
                "ctx",
                List.of(),
                "image|nginx:1.25",
                null),
            new QaQuestionResponse("Yes.", List.of(), List.of(), List.of()));

    assertTrue(repository.deleteConversation("user-1", conversationId));
    assertFalse(repository.deleteConversation("user-2", conversationId));
    assertTrue(repository.findRecentConversations("user-1", "image|nginx:1.25", 10).isEmpty());
  }
}
