### Create scan
POST http://localhost:8080/api/v1/scans
Content-Type: application/json

{
  "image": "nginx:1.25",
  "options": {
    "ignoreUnfixed": true,
    "timeoutSec": 120
  }
}

### After you get scanId, fetch normalized
GET http://localhost:8080/api/v1/scans/b07cb1e4-ae84-4f92-a6ca-aca8c4491899

### Fetch raw Trivy JSON
GET http://localhost:8080/api/v1/scans/b07cb1e4-ae84-4f92-a6ca-aca8c4491899?raw=true