### Create scan
POST http://localhost:8080/api/v1/scans
Content-Type: application/json

{
  "image": "nginx:1.25",
  "options": {
    "ignoreUnfixed": true,
    "timeoutSec": 120
  }
}

### After you get scanId, fetch normalized
GET http://localhost:8080/api/v1/scans/879e40f5-7954-45d1-b68e-71ce7d0126e5

### Fetch raw Trivy JSON
GET http://localhost:8080/api/v1/scans/b9313596-7835-49d9-965e-a9dd567ef6d4?raw=true